#!/bin/bash -ex

CLAYMORE_DIRECTORY="/etc/claymore"
CLAYMORE_SERVICE_NAME="claymore.service"
CLAYMORE_USER_GROUP=claymore

function claymore_init() {
  # install deps
  console_log "Installing dependencies (curl, wget, jq)..."
  sudo apt-get install -y curl wget jq

  # create user
  console_log "Creating the Claymore user..."
  sudo useradd $CLAYMORE_USER_GROUP

  # create group
  console_log "Creating the Claymore group..."
  sudo groupadd $CLAYMORE_USER_GROUP

  # add user to group
  console_log "Adding the Claymore user the Claymore group..."
  sudo usermod -a -G $CLAYMORE_USER_GROUP $CLAYMORE_USER_GROUP

  # add current user to group
  console_log "Adding the current user the Claymore group..."
  sudo usermod -a -G $CLAYMORE_USER_GROUP $USER

  # create directory
  console_log "Creating the Claymore destination directory..."
  mkdir -p $CLAYMORE_DIRECTORY

  # service
  console_log "Copying configuration files to their destinations..."
  sudo cp ./configs/$CLAYMORE_SERVICE_NAME /etc/systemd/system
  sudo cp ./configs/claymore.sh $CLAYMORE_DIRECTORY
}

function claymore_install() {
  local tmp_dir="/tmp/claymore"
  local staging_dir="./staging"
  local github_url="https://api.github.com/repos/nanopool/Claymore-Dual-Miner/releases/latest"
  local claymore_download_url="$(curl --silent $github_url | jq -r '.assets[0].browser_download_url')"
  local claymore_download_pkg="$(basename $claymore_download_url)"

  # create directories
  mkdir -p $tmp_dir
  mkdir -p $CLAYMORE_DIRECTORY

  # download and unzip pacakge
  console_log "Downloading the latest Claymore miner..."
  pushd $tmp_dir
  wget $claymore_download_url
  tar zxvf "$claymore_download_pkg"

  # copy files
  console_log "Copying Claymore files to the claymore directory.."
  for path in ./*/; do
    mv -i "${path//"\\\\'"/_}" "./staging/"
    cp "./staging/*.bin" $CLAYMORE_DIRECTORY
    cp "./staging/*.bin2" $CLAYMORE_DIRECTORY
    cp "./staging/ethdcrminer64" $CLAYMORE_DIRECTORY
    rm -rf "./staging"
  done
  popd

  # cleanup
  console_log "Cleaning up the install process..."
  rm -rf $tmp_dir
}

function claymore_permissions() {
  console_log "Syncing permissions..."
  sudo chown -R $CLAYMORE_USER_GROUP:$CLAYMORE_USER_GROUP $CLAYMORE_DIRECTORY
  sudo chmod -R g+rw $CLAYMORE_DIRECTORY
  sudo chmod g+x $CLAYMORE_DIRECTORY/ethdcrminer64
  sudo chmod g+x $CLAYMORE_DIRECTORY/claymore.sh
}

function claymore_config() {
  local claymore_wallet=$1
  local claymore_pool=$2

  # create directory
  mkdir -p $CLAYMORE_DIRECTORY

  # write configuration
  console_log "Writing configuration files to disk..."
  echo $claymore_wallet > $CLAYMORE_DIRECTORY/wallet.txt
  echo $claymore_pool > $CLAYMORE_DIRECTORY/pool.txt
}

function claymore_start() {
  console_log "Starting the service..."
  sudo systemctl start $CLAYMORE_SERVICE_NAME

  console_log "Enabling the service to start on boot..."
  sudo systemctl enable $CLAYMORE_SERVICE_NAME
}

function claymore_stop() {
  console_log "Stopping the service..."
  sudo systemctl stop $CLAYMORE_SERVICE_NAME

  console_log "Disabiling the service from starting on boot..."
  sudo systemctl disable $CLAYMORE_SERVICE_NAME
}

function claymore_tail() {
  sudo journalctl -u claymore -f
}

function console_log() {
  echo -e "\033[1;34m=> $1\033[0m"
}

function console_success() {
  echo -e "\033[0;32m=> $1\033[0m"
}

function console_error() {
  echo -e "\033[0;31m=> $1\033[0m"
}

if [ "$1" = "install" ]; then
  claymore_init
  claymore_permissions
  claymore_install
  claymore_permissions
  claymore_config $2 $3
  claymore_permissions
elif [ "$1" = "update" ]; then
  claymore_install
  claymore_permissions
elif [ "$1" = "config" ]; then
  claymore_stop
  claymore_config $2 $3
  claymore_permissions
  claymore_start
elif [ "$1" = "start" ]; then
  claymore_start
elif [ "$1" = "stop" ]; then
  claymore_stop
elif [ "$1" = "tail" ]; then
  claymore_tail
else
  console_error "Command Not Found"
  exit 1
fi
